openapi: 3.0.0
info:
  title: SmartShip trajectory predictive API
  version: "1.0.0"
  description: Predictive Trajectory API

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: localhost:1302
    description: Development server on local mashine

paths:
  /trajectory/{shipId}:
    description: "Ship predictive maintenance report"
    get:
      operationId: "get ship trajectory"
      summary: get ship predicted trajectory
      tags:
        - Trajectory
      parameters:
        - name: shipId
          in: path
          required: true
          description: Ship id
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/ShipTrajectoryResponse"
        "400":
          $ref: "#/components/responses/400Error"
components:
  securitySchemes:
    BaisicAuth:
      type: http
      scheme: basic
  schemas:
    Metadata:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
          example: "admin@smartship.eu"
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string
          example: "user@smartship.eu"
    PredictedPosition:
      type: object
      properties:
        latitude:
          type: number
          example: 37.757285
        longitude:
          type: number
          example: 23.626491
        predictedTime:
          type: string
          format: date-time
        accuracity:
          type: number
          maximum: 100
          minimum: 0
          example: 76
  responses:
    ShipTrajectoryResponse:
      description: "Ship predictive maintenance report"
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
              metadata:
                $ref: "#/components/schemas/Metadata"
              prediction:
                type: array
                items:
                  $ref: "#/components/schemas/PredictedPosition"

    400Error:
      description: Invalid request
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid request"
