openapi: 3.0.0
info:
  title: SmartShip weather trajectory optimazation API
  version: "1.0.0"
  description: Weather trajectory optimazation API

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: localhost:1302
    description: Development server on local mashine

paths:
  /trajectory/{shipId}:
    description: "Ship predictive maintenance report"
    get:
      operationId: "get ship trajectory"
      summary: get ship predicted trajectory
      tags:
        - Trajectory
      parameters:
        - in: path
          name: shipId
          required: true
          description: Ship id
          schema:
            type: string
        - in: query
          name: destLatt
          description: Geografical latitude of destination
          schema:
            type: number
        - in: query
          name: destLong
          description: Geografical longitude of destination
          schema:
            type: number
        - in: query
          name: startTime
          description: Starting time in milis since epoc
          schema:
            type: number
        - in: query
          name: destTime
          description: Destination time in milis since epoc
          schema:
            type: number
      responses:
        "200":
          $ref: "#/components/responses/ShipTrajectoryResponse"
        "400":
          $ref: "#/components/responses/400Error"
        "401":
          $ref: "#/components/responses/401Unauthorized"
        "406":
          $ref: "#/components/responses/406NotAcceptable"
components:
  securitySchemes:
    BaisicAuth:
      type: http
      scheme: basic
  schemas:
    Metadata:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
          example: "admin@smartship.eu"
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string
          example: "user@smartship.eu"
    PredictedPosition:
      type: object
      properties:
        latitude:
          type: number
          example: 37.757285
        longitude:
          type: number
          example: 23.626491
        predictedTime:
          type: string
          format: date-time
        accuracity:
          type: number
          maximum: 100
          minimum: 0
          example: 76
  responses:
    ShipTrajectoryResponse:
      description: "Ship predictive maintenance report"
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
              metadata:
                $ref: "#/components/schemas/Metadata"
              prediction:
                type: array
                items:
                  $ref: "#/components/schemas/PredictedPosition"
    400Error:
      description: Invalid request
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid request"
    401Unauthorized:
      description: Unauthorized request
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Unauthorized"
    406NotAcceptable:
      description: Bad parameters
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Can't find route with given parameters"
